### ISSUE TITLE
Automatizzare "Anno Accademico"

### ISSUE THREAD

**Issue by giuseppe998e** [neeggabyte/neeggabyte.github.io#1]
#### Potreste automatizzare il calcolo dell'anno accademico utilizzando una cosa del tipo:
```html
<p>Gli admin del neeggabyte vi augurano un buon anno accademico <span id="js-aa"></span>! Non esitate a contattarci anche in privato per chiedere aiuto</p>
<script>
  !function() {
    const dateNow = new Date(),
          isOctober = dateNow.getMonth() > 8, /* 0 ... 11 */
          firstHalf  = dateNow.getFullYear() - 1 * !isOctober,
          secondHalf = dateNow.getFullYear() + 1 * isOctober
          
    document.getElementById("js-aa").innerText = `${firstHalf}/${secondHalf}`
  }()
</script>
```

---
https://github.com/neeggabyte/neeggabyte.github.io/blob/1837da506ee584db06f1f8ee276e7fe2de5a1513/index.html#L34-L36

**Comment by giuseppe998e** [comment]
@federicotorrielli @stefa168

**Comment by federicotorrielli** [comment]
Ciao @giuseppe998e ! Mi pare una buona idea, vuoi fare una pull request o ci pensiamo noi?

EDIT: se fai una pull request mi raccomando non mettere il codice JS direttamente dentro HTML, ma fanne uno separato dentro una nuova cartella js così da meglio gestire la modifica in futuro se ci dovessero essere problemi.

**Comment by stefa168** [comment]
Secondo me una pull ci sta, vedi tu come preferisci @giuseppe998e 😉

**Comment by giuseppe998e** [comment]
> Ciao @giuseppe998e ! Mi pare una buona idea, vuoi fare una pull request o ci pensiamo noi?
> 
> EDIT: se fai una pull request mi raccomando non mettere il codice JS direttamente dentro HTML, ma fanne uno separato dentro una nuova cartella js così da meglio gestire la modifica in futuro se ci dovessero essere problemi.

Pardon, ho letto l'EDIT in ritardo...
Comunque essendo una riga di codice (secondo me) il JS è superfluo

**Comment by giuseppe998e** [comment]
Ditemi voi

**Comment by stefa168** [comment]
Spettacolare che stiamo usando l'issue di git come una chat in tempo reale

**Comment by federicotorrielli** [comment]
> > Ciao @giuseppe998e ! Mi pare una buona idea, vuoi fare una pull request o ci pensiamo noi?
> > EDIT: se fai una pull request mi raccomando non mettere il codice JS direttamente dentro HTML, ma fanne uno separato dentro una nuova cartella js così da meglio gestire la modifica in futuro se ci dovessero essere problemi.
> 
> Pardon, ho letto l'EDIT in ritardo

Ahah non ti preoccupare, fallo solo se hai tempo, altrimenti ci pensiamo noi.
La cartella JS più che altro ci servirà in futuro quindi se magari iniziamo con questa modifica non sarebbe male aggiungere altra roba in futuro.

**Comment by giuseppe998e** [comment]
Sistemato @federicotorrielli
