### ISSUE TITLE
Layout per mobile

### ISSUE THREAD

**Issue by federicotorrielli** [neeggabyte/neeggabyte.github.io#6]
Come da titolo. Potremmo utilizzare il nuovo framework CSS inserito da @EmanueleSpadaro per farne anche una versione mobile?

Metto tra gli Assignees me, nella speranza che voglia divertirsi a farlo prima lui 😄

**Comment by EmanueleSpadaro** [comment]
Garantisco che il sito è mobile-first, cerco di capire perché non sia così nel master
